// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import BreadcrumbsController from "./breadcrumbs_controller"
application.register("breadcrumbs", BreadcrumbsController)

import ButtonController from "./button_controller"
application.register("button", ButtonController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DownloadController from "./download_controller"
application.register("download", DownloadController)

import DragDropEditorController from "./drag_drop_editor_controller"
application.register("drag-drop-editor", DragDropEditorController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)

import MediaController from "./media_controller"
application.register("media", MediaController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import MultiSelectController from "./multi_select_controller"
application.register("multi-select", MultiSelectController)

import SearchFilterController from "./search_filter_controller"
application.register("search-filter", SearchFilterController)

import SectionSortableController from "./section_sortable_controller"
application.register("section-sortable", SectionSortableController)

import SegmentedControlController from "./segmented_control_controller"
application.register("segmented-control", SegmentedControlController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TextTrixController from "./text_trix_controller"
application.register("text-trix", TextTrixController)

import UploaderController from "./uploader_controller"
application.register("uploader", UploaderController)

import VideoController from "./video_controller"
application.register("video", VideoController)
