meta_product_name: "Akademy project"
meta_title: "Akademy project - Connection based learning"
meta_description: "We help teachers, trainers, coaches and gurus to not only create content, but also a thriving community based around their teachings. We call it: Connection based learning."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@akademy_project"   # required for Twitter Cards
