meta_product_name: "Hubbbi"
meta_title: "Hubbbi - Online learning hub"
meta_description: "Create your own custom online learning hub built around your own community and branding that keeps students on your platform and away from distractions and multiple apps."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
fb_app_id: 360022482499431
twitter_account: "@hubbbi_"   # required for Twitter Cards
